import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { Video, Upload, ShieldCheck, ShieldX, ShieldAlert, Clock3, AlertTriangle, Wand2, Cpu, DoorOpen, DoorClosed, ImagePlus } from "lucide-react";
import { useALPR, SIM_SAMPLES, type SimKind } from "@/context/ALPRContext";
import { Panel, PageHeader, Metric, PlateBadge } from "@/components/alpr/ui";
import { VehicleScene, PlateCrop } from "@/components/alpr/VehicleScene";
import { Button } from "@/components/ui/button";
import { fmtPlate, fmtTime } from "@/lib/alpr/utils";
import type { Detected, ScanResult } from "@/lib/alpr/types";
import { cn } from "@/lib/utils";
import { api } from "@/services/api";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Live Gate Monitor — smart gate ai" },
      { name: "description", content: "Real-time license plate scanning, AI access decisions and boom barrier control for security guards." },
      { property: "og:title", content: "Live Gate Monitor — smart gate ai" },
      { property: "og:description", content: "Real-time license plate scanning, AI access decisions and boom barrier control." },
    ],
  }),
  component: Monitor,
});

function LiveFeed() {
  const { rtspUrl } = useALPR();
  return (
    <div>
      <div className="relative flex aspect-[5/3] flex-col items-center justify-center overflow-hidden rounded-lg border border-border bg-black/80">
        <Video className="h-12 w-12 text-muted-foreground/50 mb-2" />
        <div className="font-mono text-sm text-muted-foreground">NO LIVE VIDEO STREAM</div>
        <div className="absolute left-3 top-3 flex items-center gap-2 rounded bg-background/80 px-2 py-1 font-mono text-[10px]">
          <span className="h-2 w-2 rounded-full bg-muted-foreground" />OFFLINE
        </div>
        <div className="absolute bottom-3 left-3 max-w-[70%] truncate rounded bg-background/80 px-2 py-1 font-mono text-[10px] text-muted-foreground">{rtspUrl}</div>
      </div>
      <div className="mt-3 flex flex-wrap gap-2">
        <Button size="sm" disabled><Cpu className="h-4 w-4" />Capture & Scan Frame</Button>
      </div>
    </div>
  );
}

function UploadPanel() {
  const { handleScanResult } = useALPR();
  const [drag, setDrag] = useState(false);
  const [busy, setBusy] = useState(false);
  const inp = useRef<HTMLInputElement>(null);
  const handle = async (f?: File) => {
    if (!f || !/image\/(jpeg|png)/.test(f.type)) return;
    setBusy(true);
    try {
      if (api.isOnline()) {
        const res = await api.scanImage(f);
        // Sync the log generated by the backend and show UI
        handleScanResult(res); 
      }
    } catch (e) {
      console.error(e);
    } finally {
      setBusy(false);
    }
  };
  return (
    <div>
      <div
        onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
        onDragLeave={() => setDrag(false)}
        onDrop={(e) => { e.preventDefault(); setDrag(false); handle(e.dataTransfer.files[0]); }}
        onClick={() => inp.current?.click()}
        className={cn("flex aspect-[5/3] cursor-pointer flex-col items-center justify-center gap-2 rounded-lg border-2 border-dashed text-center transition", drag ? "border-primary bg-primary/10" : "border-border hover:border-primary/60")}
      >
        <ImagePlus className="h-10 w-10 text-muted-foreground" />
        <div className="font-medium">{busy ? "Running YOLOv8 + OCR…" : "Drop a real vehicle photo or click to browse"}</div>
        <div className="text-xs text-muted-foreground">JPEG / PNG</div>
        <input ref={inp} type="file" accept="image/jpeg,image/png" className="hidden" onChange={(e) => handle(e.target.files?.[0])} />
      </div>
    </div>
  );
}

function Banner({ r }: { r: ScanResult }) {
  const map = {
    resident: ["bg-success text-success-foreground", ShieldCheck, "ACCESS GRANTED — RESIDENT"],
    visitor: ["bg-warning text-warning-foreground", Clock3, `VISITOR GRANTED — Valid until ${r.pass ? fmtTime(r.pass.expiresAt) : "10:00 PM"}`],
    denied: ["bg-destructive text-destructive-foreground", ShieldX, "ACCESS DENIED — UNREGISTERED VEHICLE"],
    mismatch: ["bg-destructive text-destructive-foreground", ShieldX, "ACCESS HELD — VERIFY VEHICLE"],
    fuzzy: r.resolved ? ["bg-success text-success-foreground", ShieldCheck, "ACCESS GRANTED — OCR CORRECTED"] : ["bg-primary text-primary-foreground", Wand2, "LOW-CONFIDENCE READ — GUARD REVIEW"],
    blacklisted: ["bg-destructive text-destructive-foreground animate-pulse", ShieldAlert, "CRITICAL ALERT: BLACKLISTED VEHICLE DETECTED"],
  } as const;
  const [cls, Icon, text] = map[r.kind] as unknown as [string, typeof ShieldCheck, string];
  return <div className={cn("flex items-center gap-3 rounded-lg px-4 py-3 text-base font-bold tracking-wide", cls)}><Icon className="h-6 w-6 shrink-0" />{text}</div>;
}

function Output() {
  const { current: r, confirmFuzzy } = useALPR();
  if (!r) return (
    <Panel title="AI scan results" icon={<Cpu className="h-4 w-4" />} className="flex min-h-[420px] flex-col">
      <div className="flex flex-1 flex-col items-center justify-center text-center text-muted-foreground">
        <ScanLine className="mb-3 h-10 w-10" />Waiting for a vehicle. Capture a frame, upload a photo, or use the simulator.
      </div>
    </Panel>
  );
  const muddy = r.kind === "fuzzy";
  const box = r.kind === "blacklisted" || r.kind === "denied" || r.kind === "mismatch" ? "var(--destructive)" : "var(--success)";
  return (
    <Panel title="AI scan results" icon={<Cpu className="h-4 w-4" />} actions={<span className="font-mono text-xs text-muted-foreground">{fmtTime(r.ts)}</span>}>
      <div key={r.id} className="animate-fade-in space-y-4">
        <Banner r={r} />
        {r.kind === "mismatch" && (
          <div className="flex gap-3 rounded-lg border border-warning/50 bg-warning/10 p-3 text-sm">
            <AlertTriangle className="h-5 w-5 shrink-0 text-warning" />
            <div><div className="font-semibold text-warning">Plate / Vehicle Type Mismatch Flagged</div>
              Plate {fmtPlate(r.plate)} is registered to a <b>{r.vehicle?.color} {r.vehicle?.type} ({r.vehicle?.make})</b>, but the camera sees a <b>{r.detected.color} {r.detected.type}</b>. Possible cloned or stolen plate.</div>
          </div>
        )}
        {r.kind === "fuzzy" && r.vehicle && (
          <div className="rounded-lg border border-primary/50 bg-primary/10 p-3 text-sm">
            <div className="flex items-center gap-2 font-semibold text-primary"><Wand2 className="h-4 w-4" />Fuzzy OCR correction</div>
            <p className="mt-1">OCR read <span className="font-mono font-bold">{fmtPlate(r.ocr)}</span>. <b>{r.matchPct}% match</b> with resident plate <PlateBadge plate={r.vehicle.plate} /> ({r.vehicle.owner}, {r.vehicle.flat}).</p>
            <Button className="mt-3" size="sm" disabled={r.resolved} onClick={confirmFuzzy}>{r.resolved ? "Confirmed" : "Confirm & Grant Access"}</Button>
          </div>
        )}
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="relative overflow-hidden rounded-lg border border-border">
            {r.imageUrl ? (
              <div className="relative"><img src={r.imageUrl} alt="Uploaded vehicle" className="aspect-[5/3] w-full object-cover" />
                <div className="absolute left-[36%] top-[62%] h-[16%] w-[28%] border-2" style={{ borderColor: box }} /></div>
            ) : (
              <VehicleScene className="w-full" color={r.detected.color} type={r.detected.type} plate={muddy ? (r.vehicle?.plate ?? r.ocr) : r.plate} muddy={muddy} boxColor={box} label={`yolov8 ${(r.yolo / 100).toFixed(2)}`} />
            )}
          </div>
          <div className="space-y-3">
            <div><div className="mb-1 text-xs text-muted-foreground">Cropped plate</div><PlateCrop plate={muddy ? (r.vehicle?.plate ?? r.ocr) : r.plate} muddy={muddy} /></div>
            <div><div className="text-xs text-muted-foreground">OCR text</div><div className="font-mono text-3xl font-extrabold tracking-wider">{fmtPlate(r.ocr)}</div></div>
            <div><div className="text-xs text-muted-foreground">Vehicle classification</div><div className="font-semibold">{r.detected.color} {r.detected.make} <span className="text-muted-foreground">· {r.detected.type}</span></div></div>
            {r.vehicle && <div className="text-sm text-muted-foreground">Registered: {r.vehicle.owner} · {r.vehicle.flat}</div>}
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <Metric label="Detection Speed" value={`${r.speed} ms`} />
          <Metric label="YOLO Confidence" value={`${r.yolo}%`} tone="success" />
          <Metric label="OCR Confidence" value={`${r.ocrConf}%`} tone={r.ocrConf < 80 ? "warning" : "success"} />
        </div>
      </div>
    </Panel>
  );
}

function Barrier() {
  const { barrier, openBarrier } = useALPR();
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const t = setInterval(() => setNow(Date.now()), 200); return () => clearInterval(t); }, []);
  const left = barrier.closesAt ? Math.max(0, Math.ceil((barrier.closesAt - now) / 1000)) : 0;
  return (
    <Panel title="Gate control hardware" icon={barrier.open ? <DoorOpen className="h-4 w-4" /> : <DoorClosed className="h-4 w-4" />}>
      <div className="flex items-center gap-5">
        <svg viewBox="0 0 120 60" className="h-16 w-32">
          <rect x="4" y="30" width="14" height="28" rx="2" fill="var(--muted-foreground)" />
          <g style={{ transformOrigin: "11px 34px", transform: `rotate(${barrier.open ? -80 : 0}deg)`, transition: "transform .8s" }}>
            <rect x="11" y="31" width="104" height="6" rx="3" fill={barrier.open ? "var(--success)" : "var(--destructive)"} />
          </g>
        </svg>
        <div>
          <div className="text-xs text-muted-foreground">Physical Boom Barrier</div>
          <div className={cn("text-2xl font-extrabold", barrier.open ? "text-success" : "text-destructive")}>{barrier.open ? "OPEN" : "CLOSED"}</div>
          <div className="font-mono text-xs text-muted-foreground">{barrier.override ? "Held by emergency override" : barrier.open ? `Auto-close in ${left}s` : "Locked · awaiting authorised vehicle"}</div>
        </div>
        <Button variant="outline" size="sm" className="ml-auto" onClick={() => openBarrier(5)} disabled={barrier.open}>Manual open</Button>
      </div>
    </Panel>
  );
}

function Monitor() {
  const [mode, setMode] = useState<"live" | "upload">("live");
  const { logs } = useALPR();
  return (
    <div>
      <PageHeader title="Live Gate Monitor & Scanner" subtitle="Real-time ALPR pipeline · YOLOv8 detection + OCR" />
      <div className="grid gap-5 xl:grid-cols-2">
        <div className="space-y-5">
          <Panel title="Scanning input" actions={
            <div className="flex rounded-md border border-border p-0.5 text-xs">
              {(["live", "upload"] as const).map((m) => (
                <button key={m} onClick={() => setMode(m)} className={cn("flex items-center gap-1.5 rounded px-2.5 py-1.5", mode === m ? "bg-primary text-primary-foreground" : "text-muted-foreground")}>
                  {m === "live" ? <Video className="h-3.5 w-3.5" /> : <Upload className="h-3.5 w-3.5" />}{m === "live" ? "Live RTSP Video Stream" : "Manual File Upload"}
                </button>
              ))}
            </div>
          }>
            {mode === "live" ? <LiveFeed /> : <UploadPanel />}
          </Panel>
          <Barrier />
        </div>
        <div className="space-y-5">
          <Output />
          <Panel title="Recent events">
            <ul className="divide-y divide-border text-sm">
              {logs.slice(0, 5).map((l) => (
                <li key={l.id} className="flex items-center gap-3 py-2">
                  <span className="w-14 font-mono text-xs text-muted-foreground">{fmtTime(l.ts)}</span>
                  <PlateBadge plate={l.plate} />
                  <span className="truncate text-muted-foreground">{l.note}</span>
                </li>
              ))}
            </ul>
          </Panel>
        </div>
      </div>
    </div>
  );
}

function ScanLine(props: { className?: string }) {
  return <Cpu {...props} />;
}
